---
title: "uninjured_injured_integration - Separated samples"
author: "Victor Barrera"
date: ""
output: html_document
params:
    vars_to_regress: !r c("nFeature_RNA","percent.mito")
    outputDir: "."
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r message=FALSE ,warning = FALSE}
# Shared R Markdown settings
if (file.exists("_setup.R")) {
    source("_setup.R")
}
```

```{r}
# Create folders
resultsDir <- file.path(params$outputDir, "results",Sys.Date())
resultsDir_inj <- file.path(resultsDir, "inj")
resultsDir_uninj <- file.path(resultsDir, "uninj")
resultsDir_all <- file.path(resultsDir, "all")
invisible(mapply(
    FUN = dir.create,
    list(resultsDir, resultsDir_inj, resultsDir_uninj, resultsDir_all),
    MoreArgs = list(recursive = TRUE, showWarnings = FALSE)
))


```

```{r}
# Specify seed for reproducibility
set.seed(1234567890)
```

```{r check-library-functions, echo=FALSE, message=FALSE}
'%!in%' <- function(x,y)!('%in%'(x,y))


# function to check installed libraries
check_install = function(packages) {
    not_installed = setdiff(packages, rownames(installed.packages()))
    if (length(not_installed) > 0) {
        write(paste("The libraries", not_installed, "are not installed, aborting.",
                    sep = " "), stderr())
        stop()
    }
}
```

```{r load-libraries, echo=FALSE, message=FALSE, warning=FALSE}
# load requiered library after checking if installed
packages = c("Seurat", "reticulate","AnnotationHub","ggplot2","cowplot", "dplyr")
check_install(packages)
installed = lapply(packages, library, character.only = TRUE)
```

```{r}
# load conda environment that contains umap-learning for umap plots
use_condaenv("bioPython", conda = "/Users/victorbarrera/software/miniconda2/bin/conda", required = TRUE)
```

```{r}
ah <- AnnotationHub()
ahDb <- query(ah, pattern = c("Drosophila Melanogaster","EnsDb") )

id <- ahDb %>% 
     mcols() %>%  
        rownames() %>%
        tail(n = 1)

## Download the appropriate Ensembldb database
ahEnsdb <- ahDb[[id]]

rows <- genes(ahEnsdb)  %>% 
    as.data.frame() %>% 
    dplyr::mutate(gene_name = toupper(gene_name)) %>% 
    dplyr::select(c(gene_id,gene_name))
```

```{r, load-data}
# Injured

## Metadata
## We use the metadata samples in order to choose the samples to use
metadata_injured <- read.csv("./metadata/injured/metadata.csv",header = T)
colnames(metadata_injured) <- gsub("barcodes","barcode",colnames(metadata_injured))

## 10x samples
B2.data <- Read10X(data.dir = "./data/injured/10x/B2")
B2_selected_cells <- metadata_injured %>% dplyr::filter(sample == "10X_injured_B2")%>% 
    dplyr::filter(barcode %in% colnames(B2.data))
B2_selected_cells$barcode <- as.character(B2_selected_cells$barcode)
selected_data <- B2.data[,B2_selected_cells$barcode]


B2_selected_cells$sample <- droplevels(B2_selected_cells$sample) 
pre_regressed_B2 <- CreateSeuratObject(counts = selected_data, min.cells = 10, min.features = 100, project = "10X_injured_B2")
pre_regressed_B2$tech <- "10x"
pre_regressed_B2$injured_st <- "injured"
pre_regressed_B2$sample <- "B2"


B4.data <- Read10X(data.dir = "./data/injured/10x/B4")
B4_selected_cells <- metadata_injured %>% dplyr::filter(sample == "10X_injured_B4") %>% 
    dplyr::filter(barcode %in% colnames(B4.data))
B4_selected_cells$sample <- droplevels(B4_selected_cells$sample) 
B4_selected_cells$barcode <- as.character(B4_selected_cells$barcode)
selected_data <- B4.data[,B4_selected_cells$barcode]


pre_regressed_B4 <- CreateSeuratObject(counts = selected_data, min.cells = 10, min.features = 100, project = "10X_injured_B4")
pre_regressed_B4$tech <- "10x"
pre_regressed_B4$injured_st <- "injured"
pre_regressed_B4$sample <- "B4"

## Indrop samples
Indrop.data_inj <- read.delim("./data/injured/indrop/counts_project4.txt",header = T,row.names = 1) %>% as.matrix()


Indrop_PC1_selected_cells <- metadata_injured %>% dplyr::filter(sample == "Indrop_PC1") %>% 
    dplyr::filter(barcode %in% colnames(Indrop.data_inj))
Indrop_PC1_selected_cells$barcode <- as.character(Indrop_PC1_selected_cells$barcode)
selected_data <- Indrop.data_inj[,Indrop_PC1_selected_cells$barcode]

pre_regressed_Indrop_PC1 <- CreateSeuratObject(counts = selected_data, min.cells = 10, min.features = 100, project = "Indrop_PC1")
pre_regressed_Indrop_PC1$tech <- "Indrop"
pre_regressed_Indrop_PC1$injured_st <- "injured"
pre_regressed_Indrop_PC1$sample <- "Indrop_PC1"



Indrop_PC2_1_selected_cells <- metadata_injured %>% dplyr::filter(sample == "Indrop_PC2_1") %>% 
    dplyr::filter(barcode %in% colnames(Indrop.data_inj))

Indrop_PC2_1_selected_cells$barcode <- as.character(Indrop_PC2_1_selected_cells$barcode)
selected_data <- Indrop.data_inj[,Indrop_PC2_1_selected_cells$barcode]

pre_regressed_Indrop_PC2_1 <- CreateSeuratObject(counts = selected_data, min.cells = 10, min.features = 100, project = "Indrop_PC2_1")
pre_regressed_Indrop_PC2_1$tech <- "Indrop"
pre_regressed_Indrop_PC2_1$injured_st <- "injured"
pre_regressed_Indrop_PC2_1$sample <- "Indrop_PC2_1"

```


```{r}
# Uninjured

## Metadata
## We use the metadata samples in order to choose the samples to use

metadata_uninjured <- read.csv("./metadata/uninjured/metadata.csv",header = T)
colnames(metadata_uninjured) <- gsub("barcodes","barcode",colnames(metadata_uninjured))

## 10x samples
B1.data <- Read10X(data.dir = "./data/uninjured/10x/B1/")
B1_selected_cells <- metadata_uninjured %>% dplyr::filter(sample == "10X_B1")%>% 
    dplyr::filter(barcode %in% colnames(B1.data))
B1_selected_cells$barcode <- as.character(B1_selected_cells$barcode)
selected_data <- B1.data[,B1_selected_cells$barcode]


pre_regressed_B1 <- CreateSeuratObject(counts = selected_data, min.cells = 10, min.features = 100, project = "10X_uninjured_B1")
pre_regressed_B1$tech <- "10x"
pre_regressed_B1$injured_st <- "uninjured"
pre_regressed_B1$sample <- "B1"


B3.data <- Read10X(data.dir = "./data/uninjured/10x/B3")
B3_selected_cells <- metadata_uninjured %>% dplyr::filter(sample == "10X_B3")%>% 
    dplyr::filter(barcode %in% colnames(B3.data))

B3_selected_cells$barcode <- as.character(B3_selected_cells$barcode)
selected_data <- B3.data[,B3_selected_cells$barcode]

pre_regressed_B3 <- CreateSeuratObject(counts = selected_data, min.cells = 10, min.features = 100, project = "10X_uninjured_B3")
pre_regressed_B3$tech <- "10x"
pre_regressed_B3$injured_st <- "uninjured"
pre_regressed_B3$sample <- "B3"


## Indrop samples
Indrop.data_uninj <- read.delim("./data/uninjured/indrop/indrop_p2.txt",header = T,row.names = 1) %>% as.matrix()


Indrop_blood2_uninj_selected_cells <- metadata_uninjured %>% dplyr::filter(sample == "blood2_TAAGGCTC") %>%
    dplyr::filter(barcode %in% colnames(Indrop.data_uninj))

Indrop_blood2_uninj_selected_cells$barcode <- as.character(Indrop_blood2_uninj_selected_cells$barcode)
selected_data <- Indrop.data_uninj[,Indrop_blood2_uninj_selected_cells$barcode]


pre_regressed_Indrop_blood2_uninj <- CreateSeuratObject(counts = selected_data, min.cells = 10, min.features = 100, project = "Indrop_blood2_uninj")

pre_regressed_Indrop_blood2_uninj$tech <- "Indrop"
pre_regressed_Indrop_blood2_uninj$injured_st <- "uninjured"
pre_regressed_Indrop_blood2_uninj$sample <- "Indrop_blood2_uninj"



Indrop_blood3_uninj_selected_cells <- metadata_uninjured %>% dplyr::filter(sample == "blood3_TAAGGCTC") %>%
    dplyr::filter(barcode %in% colnames(Indrop.data_uninj))

Indrop_blood3_uninj_selected_cells$barcode <- as.character(Indrop_blood3_uninj_selected_cells$barcode)
selected_data <- Indrop.data_uninj[,Indrop_blood3_uninj_selected_cells$barcode]

pre_regressed_Indrop_blood3_uninj <- CreateSeuratObject(counts = selected_data, min.cells = 10, min.features = 100, project = "Indrop_blood3_uninj")

pre_regressed_Indrop_blood3_uninj$tech <- "Indrop"
pre_regressed_Indrop_blood3_uninj$injured_st <- "uninjured"
pre_regressed_Indrop_blood3_uninj$sample <- "Indrop_blood3_uninj"
```



```{r, eval = FALSE}
# merge samples
pre_regress_all_data <- merge(x = pre_regressed_B2 ,y = c(pre_regressed_B4, pre_regressed_Indrop_PC1, 
                                                          pre_regressed_Indrop_PC2_1, pre_regressed_B1, pre_regressed_B3, pre_regressed_Indrop_blood2_uninj, pre_regressed_Indrop_blood3_uninj), 
                              add.cell.id = c("B2","B4","Ind_PC1","Ind_PC2_1","B1","B3","Ind_blood2","Ind_blood3"))
# Integration
pre_regress_all_data_list <- SplitObject(object = pre_regress_all_data, split.by = "sample")
```



```{r}
# merge samples
pre_regress_all_data_inj <- merge(x = pre_regressed_B2 ,y = c(pre_regressed_B4, pre_regressed_Indrop_PC1, 
                                                          pre_regressed_Indrop_PC2_1), 
                              add.cell.id = c("B2","B4","Ind_PC1","Ind_PC2_1"))
# Integration
pre_regress_all_data_list_inj <- SplitObject(object = pre_regress_all_data_inj, split.by = "sample")


# merge samples
pre_regress_all_data_uninj <- merge(x = pre_regressed_B1 ,y = c(pre_regressed_B3, pre_regressed_Indrop_blood2_uninj, pre_regressed_Indrop_blood3_uninj), 
                              add.cell.id = c("B1","B3","Ind_blood2","Ind_blood3"))
# Integration
pre_regress_all_data_list_uninj <- SplitObject(object = pre_regress_all_data_uninj, split.by = "sample")

```

# Integrate

## Injured

```{r}
pre_regress_all_data_list_inj <- pre_regress_all_data_list_inj[c("B2","B4","Indrop_PC1","Indrop_PC2_1")]
```


```{r}
for (i in 1:length(x = pre_regress_all_data_list_inj)) {
  pre_regress_all_data_list_inj[[i]] <- NormalizeData(object = pre_regress_all_data_list_inj[[i]], verbose = FALSE)
  pre_regress_all_data_list_inj[[i]] <- FindVariableFeatures(object = pre_regress_all_data_list_inj[[i]], 
                                             selection.method = "vst", nfeatures = 2000, verbose = FALSE)
}
# finding anchors

reference.list_inj <- pre_regress_all_data_list_inj[c("B2","B4","Indrop_PC1","Indrop_PC2_1")]
pre_regress_all_data_inj.anchors <- FindIntegrationAnchors(object.list = reference.list_inj, dims = 1:30)
pre_regress_all_data.integrated_inj <- IntegrateData(anchorset = pre_regress_all_data_inj.anchors, dims = 1:30)
DefaultAssay(object = pre_regress_all_data.integrated_inj) <- "integrated"
all_data.integrated_inj <- ScaleData(object = pre_regress_all_data.integrated_inj,vars.to.regress = params$vars_to_regress,verbose = FALSE)
DefaultAssay(object = all_data.integrated_inj) <- "integrated"
all_data.integrated_inj <- RunPCA(object = all_data.integrated_inj, verbose = FALSE)

```


```{r}
all_data.integrated_inj <- RunUMAP(object = all_data.integrated_inj, reduction = "pca",dims = 1:30)
all_data.integrated_inj <- RunTSNE(object = all_data.integrated_inj, reduction = "pca",dims = 1:30)
```

```{r}
## Coordinates
tSNE_coord <- FetchData(all_data.integrated_inj, vars = c("tSNE_1","tSNE_2")) %>% as.data.frame() %>% tibble::rownames_to_column(var = "cell")
umap_coord <- FetchData(all_data.integrated_inj, vars = c("UMAP_1","UMAP_2")) %>% as.data.frame() %>% tibble::rownames_to_column(var = "cell")

rio::export(tSNE_coord, file = file.path(resultsDir_inj,"inj_tSNE_coord.tsv.gz"))
rio::export(umap_coord, file = file.path(resultsDir_inj,"inj_umap_coord.tsv.gz"))
```


### Clusters {.tabset}

```{r}
# clustering, finding maker genes
all_data.integrated_inj <- FindNeighbors(object = all_data.integrated_inj, dims = 1:30)
```

```{r cluster_plots_diff_resolutions_inj}
for (res in seq(0.1,2,0.1)){
      all_data.integrated_inj <- FindClusters(all_data.integrated_inj, resolution = res,  verbose = FALSE)
      cluster_id <- FetchData(all_data.integrated_inj, vars = c("ident")) %>% as.data.frame() %>% tibble::rownames_to_column(var = "cell") %>% 
      dplyr::rename(cluster = ident)
      rio::export(cluster_id, file = file.path(resultsDir_inj,paste0("inj_res_",res, "_cluster_id.tsv.gz")))
}
```


```{r}
## Expression

expression_cells <- GetAssayData(object = all_data.integrated_inj, slot = "data") %>% as.matrix() %>% as.data.frame() %>% 
    tibble::rownames_to_column(var = "geneID")

expression_cells_geneName <-  GetAssayData(object = all_data.integrated_inj,  slot = "data") %>% as.matrix() %>% as.data.frame() %>% 
    tibble::rownames_to_column(var = "geneID") 

expression_cells_geneName <- rows %>% dplyr::inner_join(expression_cells_geneName, by = c("gene_id" = "geneID"))

rio::export(expression_cells, file = file.path(resultsDir_inj,"inj_expression_cells.tsv.gz"))
rio::export(expression_cells_geneName, file = file.path(resultsDir_inj,"inj_expression_cells_geneName.tsv.gz"))
```


## UnInjured

```{r}
pre_regress_all_data_list_uninj <- pre_regress_all_data_list_uninj[c("B1","B3","Indrop_blood2_uninj","Indrop_blood3_uninj")]
```


```{r}
for (i in 1:length(x = pre_regress_all_data_list_uninj)) {
  pre_regress_all_data_list_uninj[[i]] <- NormalizeData(object = pre_regress_all_data_list_uninj[[i]], verbose = FALSE)
  pre_regress_all_data_list_uninj[[i]] <- FindVariableFeatures(object = pre_regress_all_data_list_uninj[[i]], 
                                             selection.method = "vst", nfeatures = 2000, verbose = FALSE)
}
# finding anchors

reference.list_uninj <- pre_regress_all_data_list_uninj[c("B1","B3","Indrop_blood2_uninj","Indrop_blood3_uninj")]
pre_regress_all_data_uninj.anchors <- FindIntegrationAnchors(object.list = reference.list_uninj, dims = 1:30)
pre_regress_all_data.integrated_uninj <- IntegrateData(anchorset = pre_regress_all_data_uninj.anchors, dims = 1:30)
DefaultAssay(object = pre_regress_all_data.integrated_uninj) <- "integrated"
all_data.integrated_uninj <- ScaleData(object = pre_regress_all_data.integrated_uninj,vars.to.regress = params$vars_to_regress,verbose = FALSE)
DefaultAssay(object = all_data.integrated_uninj) <- "integrated"
all_data.integrated_uninj <- RunPCA(object = all_data.integrated_uninj, verbose = FALSE)

```


```{r}
all_data.integrated_uninj <- RunUMAP(object = all_data.integrated_uninj, reduction = "pca",dims = 1:30)
all_data.integrated_uninj <- RunTSNE(object = all_data.integrated_uninj, reduction = "pca",dims = 1:30)
```


```{r}
## Coordinates
tSNE_coord <- FetchData(all_data.integrated_uninj, vars = c("tSNE_1","tSNE_2")) %>% as.data.frame() %>% tibble::rownames_to_column(var = "cell")
umap_coord <- FetchData(all_data.integrated_uninj, vars = c("UMAP_1","UMAP_2")) %>% as.data.frame() %>% tibble::rownames_to_column(var = "cell")

rio::export(tSNE_coord, file = file.path(resultsDir_uninj,"uninj_tSNE_coord.tsv.gz"))
rio::export(umap_coord, file = file.path(resultsDir_uninj,"uninj_umap_coord.tsv.gz"))
```

### Clusters {.tabset}

```{r}
# clustering, finding maker genes
all_data.integrated_uninj <- FindNeighbors(object = all_data.integrated_uninj, dims = 1:30)
```



```{r cluster_plots_diff_resolutions_uninj}
for (res in seq(0.1,2,0.1)){
      all_data.integrated_uninj <- FindClusters(all_data.integrated_uninj, resolution = res,  verbose = FALSE)
      cluster_id <- FetchData(all_data.integrated_uninj, vars = c("ident")) %>% as.data.frame() %>% tibble::rownames_to_column(var = "cell") %>% 
      dplyr::rename(cluster = ident)
      rio::export(cluster_id, file = file.path(resultsDir_uninj,paste0("uninj_res_",res, "_cluster_id.tsv.gz")))
}
```

```{r}
## Expression

expression_cells <- GetAssayData(object = all_data.integrated_uninj, slot = "data") %>% as.matrix() %>% as.data.frame() %>% 
    tibble::rownames_to_column(var = "geneID")

expression_cells_geneName <-  GetAssayData(object = all_data.integrated_uninj,  slot = "data") %>% as.matrix() %>% as.data.frame() %>% 
    tibble::rownames_to_column(var = "geneID") 

expression_cells_geneName <- rows %>% dplyr::inner_join(expression_cells_geneName, by = c("gene_id" = "geneID"))

rio::export(expression_cells, file = file.path(resultsDir_uninj,"uninj_expression_cells.tsv.gz"))
rio::export(expression_cells_geneName, file = file.path(resultsDir_uninj,"uninj_expression_cells_geneName.tsv.gz"))
```

## All

```{r}
all_data_full_list <- list(all_data.integrated_inj = all_data.integrated_inj,all_data.integrated_uninj = all_data.integrated_uninj)
```


```{r, eval = FALSE}
for (i in 1:length(x = all_data_full_list)) {
  all_data_full_list[[i]] <- NormalizeData(object = all_data_full_list[[i]], verbose = FALSE)
  all_data_full_list[[i]] <- FindVariableFeatures(object = all_data_full_list[[i]], 
                                             selection.method = "vst", nfeatures = 2000, verbose = FALSE)
}

```

```{r}
# finding anchors

reference.list_all <- all_data_full_list[c("all_data.integrated_inj","all_data.integrated_uninj")
]
all_data_full_.anchors <- FindIntegrationAnchors(object.list = reference.list_all, dims = 1:30)
all_data_full_.integrated <- IntegrateData(anchorset = all_data_full_.anchors, dims = 1:30)
DefaultAssay(object = all_data_full_.integrated) <- "integrated"
all_data_full_.integrated <- ScaleData(object = all_data_full_.integrated,vars.to.regress = params$vars_to_regress,verbose = FALSE)
DefaultAssay(object = all_data_full_.integrated) <- "integrated"
all_data_full_.integrated <- RunPCA(object = all_data_full_.integrated, npcs = 30, verbose = FALSE)
all_data_full_.integrated <- RunUMAP(object = all_data_full_.integrated, reduction = "pca",dims = 1:30)
all_data_full_.integrated <- RunTSNE(object = all_data_full_.integrated, reduction = "pca",dims = 1:30)
```

```{r}
## Coordinates
tSNE_coord <- FetchData(all_data_full_.integrated, vars = c("tSNE_1","tSNE_2")) %>% as.data.frame() %>% tibble::rownames_to_column(var = "cell")
umap_coord <- FetchData(all_data_full_.integrated, vars = c("UMAP_1","UMAP_2")) %>% as.data.frame() %>% tibble::rownames_to_column(var = "cell")

rio::export(tSNE_coord, file = file.path(resultsDir_all,"all_tSNE_coord.tsv.gz"))
rio::export(umap_coord, file = file.path(resultsDir_all,"all_umap_coord.tsv.gz"))
```


# Clusters {.tabset}

```{r}
# clustering, finding maker genes
all_data_full_.integrated <- FindNeighbors(object = all_data_full_.integrated, dims = 1:30)
```



```{r cluster_plots_diff_resolutions_all}
for (res in seq(0.1,2,0.1)){
      all_data_full_.integrated <- FindClusters(all_data_full_.integrated, resolution = res,  verbose = FALSE)
      cluster_id <- FetchData(all_data_full_.integrated, vars = c("ident","injured_st")) %>% as.data.frame() %>% tibble::rownames_to_column(var = "cell") %>% 
      dplyr::rename(cluster = ident)
      rio::export(cluster_id, file = file.path(resultsDir_all,paste0("all_res_",res, "_cluster_id.tsv.gz")))
}
```

```{r}
## Expression

expression_cells <- GetAssayData(object = all_data_full_.integrated, slot = "data") %>% as.matrix() %>% as.data.frame() %>% 
    tibble::rownames_to_column(var = "geneID")

expression_cells_geneName <-  GetAssayData(object = all_data_full_.integrated,  slot = "data") %>% as.matrix() %>% as.data.frame() %>% 
    tibble::rownames_to_column(var = "geneID") 

expression_cells_geneName <- rows %>% dplyr::inner_join(expression_cells_geneName, by = c("gene_id" = "geneID"))

rio::export(expression_cells, file = file.path(resultsDir_all,"all_expression_cells.tsv.gz"))
rio::export(expression_cells_geneName, file = file.path(resultsDir_all,"all_expression_cells_geneName.tsv.gz"))
```
```{r}
save(all_data.integrated_inj,all_data.integrated_uninj,all_data_full_.integrated, file = file.path(resultsDir,"all_integrated_objects.Rda"))
```

