# Template for D. melanogaster scRNA-seq using Illumina prepared samples
---
details:
  - analysis: scRNA-seq
    genome_build: BDGP6
    algorithm:
      cellular_barcode_correction: 1
      minimum_barcode_depth: 1000
      sample_barcodes: /n/data1/cores/bcbio/PIs/norbert_perrimon/blood_scrnaseq/blood4/config/sample_barcodes_revcomp.txt
      transcriptome_fasta: /n/data1/cores/bcbio/PIs/norbert_perrimon/blood_scrnaseq/annotations/flybase/FB2017_06/transcriptome_2018-01-08.fasta
      umi_type: harvard-indrop-v3
upload:
  dir: /n/data1/cores/bcbio/PIs/norbert_perrimon/blood_scrnaseq/blood4/bcbio/2018-03-27
