---
title: "uninjured_injured_integration - Harmony - ObtainData"
author: "Victor Barrera"
date: ""
output: html_document
params:
    outputDir: "."
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r message=FALSE ,warning = FALSE}
# Shared R Markdown settings
if (file.exists("_setup.R")) {
    source("_setup.R")
}
```

```{r}
# Create folders
resultsDir <- file.path(params$outputDir, "results",Sys.Date(),"intersect")
invisible(mapply(
    FUN = dir.create,
    list(resultsDir),
    MoreArgs = list(recursive = TRUE, showWarnings = FALSE)
))


```

```{r}
# Specify seed for reproducibility
set.seed(1234567890)
```

```{r check-library-functions, echo=FALSE, message=FALSE}
'%!in%' <- function(x,y)!('%in%'(x,y))


# function to check installed libraries
check_install = function(packages) {
    not_installed = setdiff(packages, rownames(installed.packages()))
    if (length(not_installed) > 0) {
        write(paste("The libraries", not_installed, "are not installed, aborting.",
                    sep = " "), stderr())
        stop()
    }
}
```

```{r load-libraries, echo=FALSE, message=FALSE, warning=FALSE}
# load requiered library after checking if installed
packages = c("Seurat", "reticulate","AnnotationHub","ggplot2","cowplot", "dplyr", "harmony")
check_install(packages)
installed = lapply(packages, library, character.only = TRUE)
```

```{r}
# load conda environment that contains umap-learning for umap plots
use_condaenv("bioPython", conda = "/Users/victorbarrera/software/miniconda2/bin/conda", required = TRUE)
```

```{r}
ah <- AnnotationHub()
ahDb <- query(ah, pattern = c("Drosophila Melanogaster","EnsDb") )

id <- ahDb %>% 
     mcols() %>%  
        rownames() %>%
        tail(n = 1)

## Download the appropriate Ensembldb database
ahEnsdb <- ahDb[[id]]

rows <- genes(ahEnsdb)  %>% 
    as.data.frame() %>% 
    dplyr::mutate(gene_name = toupper(gene_name)) %>% 
    dplyr::select(c(gene_id,gene_name))
```

```{r}
ann_genes <- function(df, ann_df){
    df <- df %>% tibble::rownames_to_column(var = "gene_id")
    colnames(ann_df) <- c("gene_id","gene_name")
    joined_df <- dplyr::left_join(df, ann_df, by = "gene_id")
    joined_df <- joined_df %>% dplyr::mutate(gene_name = ifelse(is.na(gene_name),gene_id,gene_name)) 
    return(invisible(joined_df))
}
```

```{r, load-data}
# Injured

## Metadata
## We use the metadata samples in order to choose the samples to use
metadata_injured <- read.csv("./metadata/injured/metadata.csv",header = T)
colnames(metadata_injured) <- gsub("barcodes","barcode",colnames(metadata_injured))

## 10x samples
B2.data <- Read10X(data.dir = "./data/injured/10x/B2")
B2_selected_cells <- metadata_injured %>% dplyr::filter(sample == "10X_injured_B2")%>% 
    dplyr::filter(barcode %in% colnames(B2.data))
B2_selected_cells$barcode <- as.character(B2_selected_cells$barcode)
selected_data_B2 <- B2.data[,B2_selected_cells$barcode]
colnames(selected_data_B2) <- paste(colnames(selected_data_B2),"B2",sep = "_")

B4.data <- Read10X(data.dir = "./data/injured/10x/B4")
B4_selected_cells <- metadata_injured %>% dplyr::filter(sample == "10X_injured_B4") %>% 
    dplyr::filter(barcode %in% colnames(B4.data))
B4_selected_cells$sample <- droplevels(B4_selected_cells$sample) 
B4_selected_cells$barcode <- as.character(B4_selected_cells$barcode)
selected_data_B4 <- B4.data[,B4_selected_cells$barcode]
colnames(selected_data_B4) <- paste(colnames(selected_data_B4),"B4",sep = "_")


## Indrop samples
Indrop.data_inj <- read.delim("./data/injured/indrop/counts_project4.txt",header = T,row.names = 1) %>% as.matrix()


Indrop_PC1_selected_cells <- metadata_injured %>% dplyr::filter(sample == "Indrop_PC1") %>% 
    dplyr::filter(barcode %in% colnames(Indrop.data_inj))
Indrop_PC1_selected_cells$barcode <- as.character(Indrop_PC1_selected_cells$barcode)
selected_data_PC1 <- Indrop.data_inj[,Indrop_PC1_selected_cells$barcode]
colnames(selected_data_PC1) <- paste(colnames(selected_data_PC1),"PC1",sep = "_")


Indrop_PC2_1_selected_cells <- metadata_injured %>% dplyr::filter(sample == "Indrop_PC2_1") %>% 
    dplyr::filter(barcode %in% colnames(Indrop.data_inj))

Indrop_PC2_1_selected_cells$barcode <- as.character(Indrop_PC2_1_selected_cells$barcode)
selected_data_PC2_1 <- Indrop.data_inj[,Indrop_PC2_1_selected_cells$barcode]
colnames(selected_data_PC2_1) <- paste(colnames(selected_data_PC2_1),"PC2_1",sep = "_")
```


```{r}
# Uninjured

## Metadata
## We use the metadata samples in order to choose the samples to use

metadata_uninjured <- read.csv("./metadata/uninjured/metadata.csv",header = T)
colnames(metadata_uninjured) <- gsub("barcodes","barcode",colnames(metadata_uninjured))

## 10x samples
B1.data <- Read10X(data.dir = "./data/uninjured/10x/B1/")
B1_selected_cells <- metadata_uninjured %>% dplyr::filter(sample == "10X_B1")%>% 
    dplyr::filter(barcode %in% colnames(B1.data))
B1_selected_cells$barcode <- as.character(B1_selected_cells$barcode)
selected_data_B1 <- B1.data[,B1_selected_cells$barcode]
colnames(selected_data_B1) <- paste(colnames(selected_data_B1),"B1",sep = "_")


B3.data <- Read10X(data.dir = "./data/uninjured/10x/B3")
B3_selected_cells <- metadata_uninjured %>% dplyr::filter(sample == "10X_B3")%>% 
    dplyr::filter(barcode %in% colnames(B3.data))

B3_selected_cells$barcode <- as.character(B3_selected_cells$barcode)
selected_data_B3 <- B3.data[,B3_selected_cells$barcode]
colnames(selected_data_B3) <- paste(colnames(selected_data_B3),"B3",sep = "_")


## Indrop samples
Indrop.data_uninj <- read.delim("./data/uninjured/indrop/indrop_p2.txt",header = T,row.names = 1) %>% as.matrix()


Indrop_blood2_uninj_selected_cells <- metadata_uninjured %>% dplyr::filter(sample == "blood2_TAAGGCTC") %>%
    dplyr::filter(barcode %in% colnames(Indrop.data_uninj))

Indrop_blood2_uninj_selected_cells$barcode <- as.character(Indrop_blood2_uninj_selected_cells$barcode)
selected_data_Indrop_blood2_uninj <- Indrop.data_uninj[,Indrop_blood2_uninj_selected_cells$barcode]
colnames(selected_data_Indrop_blood2_uninj) <- paste(colnames(selected_data_Indrop_blood2_uninj),"Indrop_blood2_uninj",sep = "_")


Indrop_blood3_uninj_selected_cells <- metadata_uninjured %>% dplyr::filter(sample == "blood3_TAAGGCTC") %>%
    dplyr::filter(barcode %in% colnames(Indrop.data_uninj))

Indrop_blood3_uninj_selected_cells$barcode <- as.character(Indrop_blood3_uninj_selected_cells$barcode)
selected_data_Indrop_blood3_uninj <- Indrop.data_uninj[,Indrop_blood3_uninj_selected_cells$barcode]
colnames(selected_data_Indrop_blood3_uninj) <- paste(colnames(selected_data_Indrop_blood3_uninj),"Indrop_blood3_uninj",sep = "_")

```


```{r}
mitocondrial_genes <- rownames(selected_data_B1)[grepl("MT",rownames(selected_data_B1))]

subs_mito <- function(mito_genes, mat){
    for(mito_gene in mito_genes) {
        baseN <- gsub("MT-","",mito_gene)    
        pos <- which(grepl(baseN,rownames(mat)))
        rownames(mat)[pos] <- mito_gene
    }
    return(mat)

}


selected_data_PC1 <- subs_mito(mitocondrial_genes, selected_data_PC1)
selected_data_PC2_1 <- subs_mito(mitocondrial_genes, selected_data_PC2_1)
selected_data_Indrop_blood2_uninj <- subs_mito(mitocondrial_genes, selected_data_Indrop_blood2_uninj)
selected_data_Indrop_blood3_uninj <- subs_mito(mitocondrial_genes, selected_data_Indrop_blood3_uninj)
```


```{r}
samples_list <- list(selected_data_B1,selected_data_B2,selected_data_B3,selected_data_B4,selected_data_Indrop_blood2_uninj,selected_data_Indrop_blood3_uninj,selected_data_PC1,selected_data_PC2_1)

names(samples_list) <- c("selected_data_B1","selected_data_B2","selected_data_B3","selected_data_B4","selected_data_Indrop_blood2_uninj","selected_data_Indrop_blood3_uninj","selected_data_PC1","selected_data_PC2_1") 
```


```{r}
mat_list <- samples_list
genes_common <- Reduce(intersect, lapply(mat_list, row.names))
exprs_all <- Reduce(cbind, lapply(mat_list, function(x) x[genes_common, ]))
```


```{r}
all_data <- CreateSeuratObject(counts=exprs_all, project = "drosophila", min.cells = 10, min.features = 100) %>%
    Seurat::NormalizeData(verbose = FALSE) %>%
    FindVariableFeatures(selection.method = "vst", nfeatures = 2000) %>% 
    ScaleData(verbose = FALSE) %>% 
    RunPCA(pc.genes = all_data@var.genes, npcs = 30, verbose = FALSE)
```

```{r}
all_data[["percent.mito"]] <- PercentageFeatureSet(all_data, pattern = "^MT-")
```



```{r}

all_data$injured_st <- "no_injured"
all_data$tech <- "no_tech"

all_data$injured_st[grepl("B1",rownames(all_data@meta.data))] <- "uninjured" 
all_data$injured_st[grepl("B2",rownames(all_data@meta.data))] <- "injured" 
all_data$injured_st[grepl("B3",rownames(all_data@meta.data))] <- "uninjured" 
all_data$injured_st[grepl("B4",rownames(all_data@meta.data))] <- "injured" 
all_data$injured_st[grepl("PC1",rownames(all_data@meta.data))] <- "injured" 
all_data$injured_st[grepl("PC2_1",rownames(all_data@meta.data))] <- "injured" 
all_data$injured_st[grepl("blood2_uninj",rownames(all_data@meta.data))] <- "uninjured" 
all_data$injured_st[grepl("blood3_uninj",rownames(all_data@meta.data))] <- "uninjured"

all_data$tech[grepl("B1",rownames(all_data@meta.data))] <- "10x" 
all_data$tech[grepl("B2",rownames(all_data@meta.data))] <- "10x" 
all_data$tech[grepl("B3",rownames(all_data@meta.data))] <- "10x" 
all_data$tech[grepl("B4",rownames(all_data@meta.data))] <- "10x" 
all_data$tech[grepl("PC1",rownames(all_data@meta.data))] <- "Indrop" 
all_data$tech[grepl("PC2_1",rownames(all_data@meta.data))] <- "Indrop" 
all_data$tech[grepl("blood2_uninj",rownames(all_data@meta.data))] <- "Indrop" 
all_data$tech[grepl("blood3_uninj",rownames(all_data@meta.data))] <- "Indrop"
```

```{r}
options(repr.plot.height = 2.5, repr.plot.width = 6)
all_data <- all_data %>% 
    RunHarmony(c("tech","injured_st"), theta = c(10,2), plot_convergence = TRUE, max.iter.harmony = 30, verbose = FALSE)
```


```{r}
all_data <- all_data %>% 
    RunUMAP(reduction = "harmony", dims = 1:20) %>% 
    RunTSNE( reduction = "harmony",dims = 1:20) %>% 
    FindNeighbors(reduction = "harmony", dims = 1:20, verbose = FALSE, force.recalc = TRUE) %>% 
    FindClusters(resolution = seq(0.1,2,0.1), verbose = FALSE) %>% 
    identity()
```

```{r}
## Coordinates
tSNE_coord_all <- FetchData(all_data, vars = c("tSNE_1","tSNE_2")) %>% as.data.frame() %>% tibble::rownames_to_column(var = "cell")
umap_coord_all <- FetchData(all_data, vars = c("UMAP_1","UMAP_2")) %>% as.data.frame() %>% tibble::rownames_to_column(var = "cell")

rio::export(tSNE_coord_all, file = file.path(resultsDir,"all_tSNE_coord.tsv.gz"))
rio::export(umap_coord_all, file = file.path(resultsDir,"all_umap_coord.tsv.gz"))

## Injured

injured_cells <- subset(all_data, subset = injured_st == "injured")

tSNE_coord_inj <- FetchData(injured_cells, vars = c("tSNE_1","tSNE_2")) %>% as.data.frame() %>% tibble::rownames_to_column(var = "cell")
umap_coord_inj <- FetchData(injured_cells, vars = c("UMAP_1","UMAP_2")) %>% as.data.frame() %>% tibble::rownames_to_column(var = "cell")

rio::export(tSNE_coord_inj, file = file.path(resultsDir,"inj_tSNE_coord.tsv.gz"))
rio::export(umap_coord_inj, file = file.path(resultsDir,"inj_umap_coord.tsv.gz"))

## Uninjured

uninjured_cells <- subset(all_data, subset = injured_st == "uninjured")

tSNE_coord_uninj <- FetchData(uninjured_cells, vars = c("tSNE_1","tSNE_2")) %>% as.data.frame() %>% tibble::rownames_to_column(var = "cell")
umap_coord_uninj <- FetchData(uninjured_cells, vars = c("UMAP_1","UMAP_2")) %>% as.data.frame() %>% tibble::rownames_to_column(var = "cell")

rio::export(tSNE_coord_uninj, file = file.path(resultsDir,"uninj_tSNE_coord.tsv.gz"))
rio::export(umap_coord_uninj, file = file.path(resultsDir,"uninj_umap_coord.tsv.gz"))
```


```{r }
res = 0.6

selected_res <- paste0("RNA_snn_res.",res)
Idents(all_data) <- selected_res
cluster_id <- FetchData(all_data, vars = c("ident","injured_st")) %>% as.data.frame() %>% tibble::rownames_to_column(var = "cell") %>% 
dplyr::rename(cluster = ident)
rio::export(cluster_id, file = file.path(resultsDir,paste0("all_res_",res, "_cluster_id.tsv.gz")))

cluster_id_inj <- cluster_id  %>% dplyr::filter(injured_st == "injured")

rio::export(cluster_id_inj, file = file.path(resultsDir,paste0("inj_res_",res, "_cluster_id.tsv.gz")))

cluster_id_uninj <- cluster_id  %>% dplyr::filter(injured_st == "uninjured")

rio::export(cluster_id_uninj, file = file.path(resultsDir,paste0("uninj_res_",res, "_cluster_id.tsv.gz")))
```

```{r}
## Expression

expression_cells <- GetAssayData(object = all_data, slot = "data") %>% as.matrix() %>% as.data.frame() %>% 
    tibble::rownames_to_column(var = "geneID")

expression_cells_geneName <- rows %>% dplyr::inner_join(expression_cells, by = c("gene_id" = "geneID"))

rio::export(expression_cells, file = file.path(resultsDir,"all_expression_cells.tsv.gz"))
rio::export(expression_cells_geneName, file = file.path(resultsDir,"all_expression_cells_geneName.tsv.gz"))

## Injured

expression_cells_inj <- GetAssayData(object = injured_cells, slot = "data") %>% as.matrix() %>% as.data.frame() %>% 
    tibble::rownames_to_column(var = "geneID")

expression_cells_geneName_inj <- rows %>% dplyr::inner_join(expression_cells_inj, by = c("gene_id" = "geneID"))

rio::export(expression_cells_inj, file = file.path(resultsDir,"inj_expression_cells.tsv.gz"))
rio::export(expression_cells_geneName_inj, file = file.path(resultsDir,"inj_expression_cells_geneName.tsv.gz"))

## Uninjured

expression_cells_uninj <- GetAssayData(object = uninjured_cells, slot = "data") %>% as.matrix() %>% as.data.frame() %>% 
    tibble::rownames_to_column(var = "geneID")

expression_cells_geneName_uninj <- rows %>% dplyr::inner_join(expression_cells_uninj, by = c("gene_id" = "geneID"))

rio::export(expression_cells_uninj, file = file.path(resultsDir,"uninj_expression_cells.tsv.gz"))
rio::export(expression_cells_geneName_uninj, file = file.path(resultsDir,"uninj_expression_cells_geneName.tsv.gz"))
```


```{r}
Idents(all_data) <- selected_res
all_data$cluster <- Idents(all_data)
all_data$cluster[all_data$cluster %in% c(1,2,3,4,5)] <- 1
all_data$cluster <- droplevels(all_data$cluster)
Idents(all_data) <- "cluster"
```

```{r }
cluster_id <- FetchData(all_data, vars = c("ident","injured_st")) %>% as.data.frame() %>% tibble::rownames_to_column(var = "cell") %>% 
dplyr::rename(cluster = ident)
rio::export(cluster_id, file = file.path(resultsDir,paste0("all_res_",res, "_cluster_id_renamedClusters.tsv.gz")))

cluster_id_inj <- cluster_id  %>% dplyr::filter(injured_st == "injured")

rio::export(cluster_id_inj, file = file.path(resultsDir,paste0("inj_res_",res, "_cluster_id_renamedClusters.tsv.gz")))

cluster_id_uninj <- cluster_id  %>% dplyr::filter(injured_st == "uninjured")

rio::export(cluster_id_uninj, file = file.path(resultsDir,paste0("uninj_res_",res, "_cluster_id_renamedClusters.tsv.gz")))
```