---
title: "uninjured_injured_integration - Harmony - ObtainData"
author: "Victor Barrera"
date: ""
output: html_document
params:
    outputDir: "."
    integrated_file: "./results/2019-07-25/intersect/all_data.Rda"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r message=FALSE ,warning = FALSE}
# Shared R Markdown settings
if (file.exists("_setup.R")) {
    source("_setup.R")
}
```

```{r}
# Create folders
resultsDir <- file.path(params$outputDir, "results",Sys.Date(),"intersect","data")
invisible(mapply(
    FUN = dir.create,
    list(resultsDir),
    MoreArgs = list(recursive = TRUE, showWarnings = FALSE)
))


```

```{r}
# Specify seed for reproducibility
set.seed(1234567890)
```

```{r check-library-functions, echo=FALSE, message=FALSE}
'%!in%' <- function(x,y)!('%in%'(x,y))


# function to check installed libraries
check_install = function(packages) {
    not_installed = setdiff(packages, rownames(installed.packages()))
    if (length(not_installed) > 0) {
        write(paste("The libraries", not_installed, "are not installed, aborting.",
                    sep = " "), stderr())
        stop()
    }
}
```

```{r load-libraries, echo=FALSE, message=FALSE, warning=FALSE}
# load requiered library after checking if installed
packages = c("Seurat", "reticulate","AnnotationHub","ggplot2","cowplot", "dplyr", "harmony")
check_install(packages)
installed = lapply(packages, library, character.only = TRUE)
```

```{r}
# load conda environment that contains umap-learning for umap plots
use_condaenv("bioPython", conda = "/Users/victorbarrera/software/miniconda2/bin/conda", required = TRUE)
```

```{r}
ah <- AnnotationHub()
ahDb <- query(ah, pattern = c("Drosophila Melanogaster","EnsDb") )

id <- ahDb %>% 
     mcols() %>%  
        rownames() %>%
        tail(n = 1)

## Download the appropriate Ensembldb database
ahEnsdb <- ahDb[[id]]

rows <- genes(ahEnsdb)  %>% 
    as.data.frame() %>% 
    dplyr::mutate(gene_name = toupper(gene_name)) %>% 
    dplyr::select(c(gene_id,gene_name))
```

```{r}
ann_genes <- function(df, ann_df){
    df <- df %>% tibble::rownames_to_column(var = "gene_id")
    colnames(ann_df) <- c("gene_id","gene_name")
    joined_df <- dplyr::left_join(df, ann_df, by = "gene_id")
    joined_df <- joined_df %>% dplyr::mutate(gene_name = ifelse(is.na(gene_name),gene_id,gene_name)) 
    return(invisible(joined_df))
}
```

```{r, load-data}
load(params$integrated_file)
```

```{r}
## Coordinates
tSNE_coord_all <- FetchData(all_data, vars = c("tSNE_1","tSNE_2")) %>% as.data.frame() %>% tibble::rownames_to_column(var = "cell")
umap_coord_all <- FetchData(all_data, vars = c("UMAP_1","UMAP_2")) %>% as.data.frame() %>% tibble::rownames_to_column(var = "cell")

rio::export(tSNE_coord_all, file = file.path(resultsDir,"all_tSNE_coord.tsv.gz"))
rio::export(umap_coord_all, file = file.path(resultsDir,"all_umap_coord.tsv.gz"))

## Injured

injured_cells <- subset(all_data, subset = injured_st == "injured")

tSNE_coord_inj <- FetchData(injured_cells, vars = c("tSNE_1","tSNE_2")) %>% as.data.frame() %>% tibble::rownames_to_column(var = "cell")
umap_coord_inj <- FetchData(injured_cells, vars = c("UMAP_1","UMAP_2")) %>% as.data.frame() %>% tibble::rownames_to_column(var = "cell")

rio::export(tSNE_coord_inj, file = file.path(resultsDir,"inj_tSNE_coord.tsv.gz"))
rio::export(umap_coord_inj, file = file.path(resultsDir,"inj_umap_coord.tsv.gz"))

## Uninjured

uninjured_cells <- subset(all_data, subset = injured_st == "uninjured")

tSNE_coord_uninj <- FetchData(uninjured_cells, vars = c("tSNE_1","tSNE_2")) %>% as.data.frame() %>% tibble::rownames_to_column(var = "cell")
umap_coord_uninj <- FetchData(uninjured_cells, vars = c("UMAP_1","UMAP_2")) %>% as.data.frame() %>% tibble::rownames_to_column(var = "cell")

rio::export(tSNE_coord_uninj, file = file.path(resultsDir,"uninj_tSNE_coord.tsv.gz"))
rio::export(umap_coord_uninj, file = file.path(resultsDir,"uninj_umap_coord.tsv.gz"))
```


```{r }
res = 0.6

selected_res <- paste0("RNA_snn_res.",res)
Idents(all_data) <- selected_res
cluster_id <- FetchData(all_data, vars = c("ident","injured_st")) %>% as.data.frame() %>% tibble::rownames_to_column(var = "cell") %>% 
dplyr::rename(cluster = ident)
rio::export(cluster_id, file = file.path(resultsDir,paste0("all_res_",res, "_cluster_id.tsv.gz")))

cluster_id_inj <- cluster_id  %>% dplyr::filter(injured_st == "injured")

rio::export(cluster_id_inj, file = file.path(resultsDir,paste0("inj_res_",res, "_cluster_id.tsv.gz")))

cluster_id_uninj <- cluster_id  %>% dplyr::filter(injured_st == "uninjured")

rio::export(cluster_id_uninj, file = file.path(resultsDir,paste0("uninj_res_",res, "_cluster_id.tsv.gz")))
```

```{r}
## Expression

expression_cells <- GetAssayData(object = all_data, slot = "data") %>% as.matrix() %>% as.data.frame() %>% 
    tibble::rownames_to_column(var = "geneID")

expression_cells_geneName <- rows %>% dplyr::inner_join(expression_cells, by = c("gene_id" = "geneID"))

rio::export(expression_cells, file = file.path(resultsDir,"all_expression_cells.tsv.gz"))
rio::export(expression_cells_geneName, file = file.path(resultsDir,"all_expression_cells_geneName.tsv.gz"))

## Injured

expression_cells_inj <- GetAssayData(object = injured_cells, slot = "data") %>% as.matrix() %>% as.data.frame() %>% 
    tibble::rownames_to_column(var = "geneID")

expression_cells_geneName_inj <- rows %>% dplyr::inner_join(expression_cells_inj, by = c("gene_id" = "geneID"))

rio::export(expression_cells_inj, file = file.path(resultsDir,"inj_expression_cells.tsv.gz"))
rio::export(expression_cells_geneName_inj, file = file.path(resultsDir,"inj_expression_cells_geneName.tsv.gz"))

## Uninjured

expression_cells_uninj <- GetAssayData(object = uninjured_cells, slot = "data") %>% as.matrix() %>% as.data.frame() %>% 
    tibble::rownames_to_column(var = "geneID")

expression_cells_geneName_uninj <- rows %>% dplyr::inner_join(expression_cells_uninj, by = c("gene_id" = "geneID"))

rio::export(expression_cells_uninj, file = file.path(resultsDir,"uninj_expression_cells.tsv.gz"))
rio::export(expression_cells_geneName_uninj, file = file.path(resultsDir,"uninj_expression_cells_geneName.tsv.gz"))
```


```{r}
Idents(all_data) <- selected_res
all_data$cluster <- Idents(all_data)
all_data$cluster[all_data$cluster %in% c(1,2,3,4,5)] <- 1
all_data$cluster <- droplevels(all_data$cluster)
Idents(all_data) <- "cluster"
```

```{r }
cluster_id <- FetchData(all_data, vars = c("ident","injured_st")) %>% as.data.frame() %>% tibble::rownames_to_column(var = "cell") %>% 
dplyr::rename(cluster = ident)
rio::export(cluster_id, file = file.path(resultsDir,paste0("all_res_",res, "_cluster_id_renamedClusters.tsv.gz")))

cluster_id_inj <- cluster_id  %>% dplyr::filter(injured_st == "injured")

rio::export(cluster_id_inj, file = file.path(resultsDir,paste0("inj_res_",res, "_cluster_id_renamedClusters.tsv.gz")))

cluster_id_uninj <- cluster_id  %>% dplyr::filter(injured_st == "uninjured")

rio::export(cluster_id_uninj, file = file.path(resultsDir,paste0("uninj_res_",res, "_cluster_id_renamedClusters.tsv.gz")))
```