details:
- algorithm:
    cellular_barcode_correction: 1
    cellular_barcodes:
    - ~/bcbio/indrop_rnaseq/metadata/cellular_barcodes.txt
    - ~/bcbio/indrop_rnaseq/metadata/cellular_barcodes_reverse_complement.txt
    minimum_barcode_depth: 10000
    positional_umi: false
    sample_barcodes: /n/data1/cores/bcbio/PIs/norbert_perrimon/blood_scrnaseq/metadata/sample_barcodes_reverse_complement.txt
    singlecell_quantifier: rapmap
    transcriptome_fasta: ~/annotation/transcriptome/drosophila_melanogaster/dmel-all-transcript-r6.14.fasta
    umi_type: harvard-indrop-v3
  analysis: scRNA-seq
  description: combined
  files:
  - /n/data1/cores/bcbio/PIs/norbert_perrimon/blood_scrnaseq/raw_data/fastq/combined_R1.fastq.gz
  - /n/data1/cores/bcbio/PIs/norbert_perrimon/blood_scrnaseq/raw_data/fastq/combined_R2.fastq.gz
  - /n/data1/cores/bcbio/PIs/norbert_perrimon/blood_scrnaseq/raw_data/fastq/combined_R3.fastq.gz
  - /n/data1/cores/bcbio/PIs/norbert_perrimon/blood_scrnaseq/raw_data/fastq/combined_R4.fastq.gz
  genome_build: BDGP6
  metadata:
    condition: combined
fc_date: '2017-03-03'
fc_name: indrop_rnaseq
upload:
  dir: ../final
