details:
- algorithm:
    cellular_barcode_correction: 1
    minimum_barcode_depth: 1000
    sample_barcodes: /n/data1/cores/bcbio/PIs/norbert_perrimon/blood_scrnaseq/meta/run1/sample_barcodes_revcomp.txt
    singlecell_quantifier: rapmap
    transcriptome_fasta: /n/data1/cores/bcbio/PIs/norbert_perrimon/blood_scrnaseq/annotations/flybase/FB2017_04/transcriptome_2017-10-02.fasta
    umi_type: harvard-indrop-v3
  analysis: scRNA-seq
  description: run1
  files:
  - /n/data1/cores/bcbio/PIs/norbert_perrimon/blood_scrnaseq/data-raw/run1/fastq/170201_NB501807_0021_AHWCYVBGXY_R1.fastq.gz
  - /n/data1/cores/bcbio/PIs/norbert_perrimon/blood_scrnaseq/data-raw/run1/fastq/170201_NB501807_0021_AHWCYVBGXY_R2.fastq.gz
  - /n/data1/cores/bcbio/PIs/norbert_perrimon/blood_scrnaseq/data-raw/run1/fastq/170201_NB501807_0021_AHWCYVBGXY_R3.fastq.gz
  - /n/data1/cores/bcbio/PIs/norbert_perrimon/blood_scrnaseq/data-raw/run1/fastq/170201_NB501807_0021_AHWCYVBGXY_R4.fastq.gz
  genome_build: BDGP6
  metadata: {}
fc_date: '2017-10-13'
fc_name: indrop_rnaseq
upload:
  dir: /n/data1/cores/bcbio/PIs/norbert_perrimon/blood_scrnaseq/data/run1
