---
title: "uninjured_injured_integration - Separated samples"
author: "Victor Barrera"
date: ""
output: html_document
params:
    outputDir: "."
    objectFile: "../uninjured_injured_integration/results/2019-05-13/all_integrated_objects.Rda"
    resolution: "0.6"

---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r message=FALSE ,warning = FALSE}
# Shared R Markdown settings
if (file.exists("_setup.R")) {
    source("_setup.R")
}
```

```{r}
# Create folders
resultsDir <- file.path(params$outputDir, "results",Sys.Date())
invisible(mapply(
    FUN = dir.create,
    list(resultsDir),
    MoreArgs = list(recursive = TRUE, showWarnings = FALSE)
))


```

```{r}
# Specify seed for reproducibility
set.seed(1234567890)
```

```{r check-library-functions, echo=FALSE, message=FALSE}
'%!in%' <- function(x,y)!('%in%'(x,y))

# function to check installed libraries
check_install = function(packages) {
    not_installed = setdiff(packages, rownames(installed.packages()))
    if (length(not_installed) > 0) {
        write(paste("The libraries", not_installed, "are not installed, aborting.",
                    sep = " "), stderr())
        stop()
    }
}
```


```{r load-libraries, echo=FALSE, message=FALSE, warning=FALSE}
# load requiered library after checking if installed
packages = c("Seurat", "reticulate","AnnotationHub","ggplot2","cowplot", "dplyr","tidyr")
check_install(packages)
installed = lapply(packages, library, character.only = TRUE)
```

```{r}
# load conda environment that contains umap-learning for umap plots
use_condaenv("bioPython", conda = "/Users/victorbarrera/software/miniconda2/bin/conda", required = TRUE)
```

```{r}
ann_genes <- function(df, ann_df){
    df <- df %>% tibble::rownames_to_column(var = "gene_id")
    colnames(ann_df) <- c("gene_id","gene_name")
    joined_df <- dplyr::left_join(df, ann_df, by = "gene_id")
    joined_df <- joined_df %>% dplyr::mutate(gene_name = ifelse(is.na(gene_name),gene_id,gene_name)) 
    return(invisible(joined_df))
}
```

```{r obtain_annotation, eval = FALSE}
ah <- AnnotationHub()
ahDb <- query(ah, pattern = c("Danio rerio","EnsDb") )

id <- ahDb %>% 
     mcols() %>%  
        rownames() %>%
        tail(n = 1)

## Download the appropriate Ensembldb database
ahEnsdb <- ahDb[[id]]

rows <- genes(ahEnsdb)  %>% 
    as.data.frame() %>% 
    dplyr::mutate(gene_name = toupper(gene_name)) %>% 
    dplyr::select(c(gene_id,gene_name))

```

```{r}
load(params$objectFile) 
```

```{r}
res = params$resolution
selected_res <- paste0("integrated_snn_res.",res)
Idents(object = all_data_full_.integrated) <- selected_res
```

```{r}
DefaultAssay(all_data_full_.integrated) <- "RNA"
```

```{r}
if(file.exists(file.path(resultsDir,paste0("res_",res,"_markers.Rda"))))
{
    load(file.path(resultsDir,paste0("res_",res,"_markers.Rda")))
}else{
table_df <- table(all_data_full_.integrated@meta.data[,selected_res],all_data_full_.integrated@meta.data$injured_st) %>% 
    as.data.frame() %>% spread(key = Var2, value =Freq)
colnames(table_df)[1] <- "cluster"
markers_list <- list()
table_df_sel <- table_df %>% dplyr::filter(injured >= 3 & uninjured >= 3)
for(cluster_id in table_df_sel$cluster){
    markers <- FindConservedMarkers(all_data_full_.integrated, ident.1 = cluster_id, grouping.var = "injured_st", verbose = FALSE)
    #markers <- ann_genes(markers,rows)
    markers <- markers %>% tibble::rownames_to_column(var = "gene_id")
    markers_list[[paste0("cluster_",cluster_id)]] <- markers
}
markers_list[["cluster_12"]] <- FindMarkers(all_data_full_.integrated, ident.1 = 12) %>% tibble::rownames_to_column(var = "gene_id")
markers_list[["cluster_13"]] <- FindMarkers(all_data_full_.integrated, ident.1 = 13) %>% tibble::rownames_to_column(var = "gene_id")


save(markers_list, file = file.path(resultsDir,paste0("res_",res,"_markers.Rda")))
}
```

# Plots

## TSNE

```{r}
DimPlot(all_data_full_.integrated, reduction = "tsne", label = T)
```

## Clusters-TSNE {.tabset}

```{r plot_selected_genes_clusters_TSNE, results = "asis"}
plot_feature_plot_wrapper <- function(obj,sub_df){
    p <- FeaturePlot(obj, features = sub_df[1],cols = c("grey", "blue"), 
reduction = "tsne",min.cutoff = 1) + 
        ggtitle(sub_df[1]) %>% invisible()
    return(p)
}

for(cluster_n in names(markers_list)){
    cat("\n")
    cat("### ",cluster_n," {.tabset} \n")
    df <- markers_list[[`cluster_n`]][1:12,]
    df_split <- split(df, ceiling(seq_along(df$gene_id)/6))
    for(i in names(df_split)){
        cat("\n")
        cat("####",paste("Cluster",cluster_n,i,sep="-"),"\n")
        plot_list <- apply(df_split[[i]],1,FUN = function(x){plot_feature_plot_wrapper(all_data_full_.integrated,x)})
        p_l <- plot_grid(plotlist = plot_list,ncol = 2)
        print(p_l)
        cat("\n")
    }
    cat("\n")
}
```


## Clusters-violin {.tabset}

```{r plot_selected_genes_clusters_violin, results = "asis"}

for(cluster_n in names(markers_list)){
    cat("\n")
    cat("### ",cluster_n," {.tabset} \n")
    df <- markers_list[[`cluster_n`]][1:6,]
    df_split <- split(df, ceiling(seq_along(df$gene_id)/1))
    for(i in names(df_split)){
    cat("\n")
    cat("####",paste("Cluster",cluster_n,i,sep="-"),"\n")
    plot <- VlnPlot(all_data_full_.integrated, features =  df_split[[i]]$gene_id,  group.by = selected_res, 
    pt.size = 0, combine = FALSE)
    p <- plot[[1]]+ ggtitle(df_split[[i]]$gene_id)
    print(p)
    cat("\n")
    }
    cat("\n")
}
```

# Injured/Uninjured 

```{r}
DefaultAssay(all_data_full_.integrated) <- "RNA"
```

```{r}
all_data_full_.integrated$cluster.inj_st <- paste("cluster",Idents(all_data_full_.integrated), all_data_full_.integrated$injured_st, sep = "_")
all_data_full_.integrated$cluster <- Idents(all_data_full_.integrated)
Idents(all_data_full_.integrated) <- "cluster.inj_st"
```

```{r}
if(file.exists(file.path(resultsDir,paste0("res_",res,"_markers_injured_st.Rda"))))
{
    load(file.path(resultsDir,paste0("res_",res,"_markers_injured_st.Rda")))
}else{
table_df <- table(all_data_full_.integrated@meta.data[,selected_res],all_data_full_.integrated@meta.data$injured_st) %>% 
    as.data.frame() %>% spread(key = Var2, value =Freq)
colnames(table_df)[1] <- "cluster"
markers_list_injst <- list()
table_df_sel <- table_df %>% dplyr::filter(injured >= 3 & uninjured >= 3)
for(cluster_id in table_df_sel$cluster){
    ident_injured = paste0("cluster_",cluster_id,"_injured")
    ident_uninjured = paste0("cluster_",cluster_id,"_uninjured")
    markers <- FindMarkers(all_data_full_.integrated,  ident.1 = ident_injured, ident.2 = ident_uninjured, verbose = FALSE)
    #markers <- ann_genes(markers,rows)
    markers <- markers %>% tibble::rownames_to_column(var = "gene_id")
    markers_list_injst[[paste0("cluster_",cluster_id)]] <- markers
}
save(markers_list_injst, file = file.path(resultsDir,paste0("res_",res,"_markers_injured_st.Rda")))
}
```


## Clusters-TSNE-Injured status {.tabset}

```{r plot_selected_genes_clusters_TSNE_injst, results = "asis"}
plot_feature_plot_wrapper <- function(obj,sub_df){
    p <- FeaturePlot(obj, features = sub_df[1],cols = c("grey", "blue"), 
reduction = "tsne",min.cutoff = 1, split.by = "injured_st") + 
        ggtitle(sub_df[1]) %>% invisible()
    return(p)
}

for(cluster_n in names(markers_list_injst)){
    cat("\n")
    cat("### ",cluster_n," {.tabset} \n")
    df <- markers_list[[`cluster_n`]][1:12,]
    df_split <- split(df, ceiling(seq_along(df$gene_id)/3))
    for(i in names(df_split)){
        cat("\n")
        cat("####",paste("Cluster",cluster_n,i,sep="-"),"\n")
        plot_list <- apply(df_split[[i]],1,FUN = function(x){plot_feature_plot_wrapper(all_data_full_.integrated,x)})
        p_l <- plot_grid(plotlist = plot_list,ncol = 1)
        print(p_l)
        cat("\n")
    }
    cat("\n")
}
```


## Clusters-violin-Injured status {.tabset}

```{r plot_selected_genes_clusters_violin_injst, results = "asis"}

for(cluster_n in names(markers_list_injst)){
    cat("\n")
    cat("### ",cluster_n," {.tabset} \n")
    df <- markers_list[[`cluster_n`]][1:6,]
    df_split <- split(df, ceiling(seq_along(df$gene_id)/1))
    for(i in names(df_split)){
    cat("\n")
    cat("####",paste("Cluster",cluster_n,i,sep="-"),"\n")
    plot <- VlnPlot(all_data_full_.integrated, features =  df_split[[i]]$gene_id, split.by = "injured_st", group.by = selected_res, 
    pt.size = 0, combine = FALSE)
    p <- plot[[1]]+ ggtitle(df_split[[i]]$gene_id)
    print(p)
    cat("\n")
    }
    cat("\n")
}
```